### ISSUE TITLE
Push deleted tags (delete on remote)

### ISSUE THREAD

**Issue by rardcode** [flathub/com.syntevo.SmartGit#91]
It is possible push deleted tags (delete on remote)?
thanks

**Comment by x80486** [comment]
I don't know exactly what you are trying to do.

Is this something that's failing with the `Flatpak` format or something that you would like to know?

If you are looking for a certain information about `SmartGit`, I would recommend to stop by [UserEcho](https://smartgit.userecho.com/) because maintainers will be able to answer directly. If it's something related with the `Flatpak` format, this issue tracker is fine.

**Comment by rardcode** [comment]
hi!
i've add a tag and pushed to remote.
i've deleted tag but if i push to remote, tag are not deleted in remote

**Comment by rardcode** [comment]
excuse me....i was wrong...
when delete tag from Brabches tree....i doesn't check "remove from remote"
![test](https://github.com/flathub/com.syntevo.SmartGit/assets/50568864/2ec2d0da-6ca1-493d-ae58-b4e157cb48de)
